### ISSUE TITLE
implement the ASR algorithm from external github project into this codebase

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#11]
https://github.com/DiGyt/asrpy
careful: why zero stars?
maybe better alternatives

**Comment by nicoa47** [comment]
check py implementation: https://github.com/s4rify/rASRMatlab

**Comment by nicoa47** [comment]
open question: which calibration data to use?

[the paper:](https://www.frontiersin.org/articles/10.3389/fnhum.2019.00141/full)
> It is recommended that the calibration data have a length of at least 1 min and be recorded from the respective participant during rest under comparable recording conditions as the subsequent processing.

**Comment by nicoa47** [comment]
potential problem to run: what about amplifier disconnects? e.g. here:

![grafik](https://user-images.githubusercontent.com/15858293/184319656-45fe8cc8-5d6b-4df4-ae15-e5aa3d88b084.png)

agreement: try anyway (visual inspection?)

**Comment by caghangir-1** [comment]
Don't care about it because ASR makes corrections locally via windowing. If the disconnection or signal jumps are not within the area of interest for 4 conditions which are not because I've checked tons of times, you don't need to care about those jumps. Also, ASR works with learning based so, those little parts can't bias the main model.

**Comment by nicoa47** [comment]
assigned @caghangir-1  as per #57
