### ISSUE TITLE
implement robust preprocessing pipeline

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#15]
checks that overcleaning is avoided!

important concepts/tools to learn:
- #12 
- #20 
- #17 

find quantifiable measures:
- #18 
- #19 

sort the data:
- #7 

components of original plan, may not be needed:
- #11 
- #10 
- #7 
- #8 

questions:
- how many channels are needed for ASR?

**Comment by caghangir-1** [comment]
We will not use ASR but will use rASR, so there might be locally different values for each dataset, but since pyPREP will equalize the amplitude range in a robust way so, the approximate standard deviation is becoming "5" unit which rASR used as a default cutoff = 5. win_length will be 5 seconds which is our customization regarding to the length of sleep evoked potentials (micro awakenings, k-complexes, spindles). win_overlaps= 50% is roughly the best.

parameters:
* method = 'riemann'
* cutoff = 5
* win_len = 5
* win_overlap = 2.5
* estimator = 'lwf' (we need regularization so that's why we use it which uses pyriemann package).

**Comment by nicoa47** [comment]
This robust way is replaced by the final decisions regarding preprocessing, as noted in the wiki: https://github.com/nicoa47/LDEEG/wiki/Final-decisions-about-preprocessing
